DROP TABLE  user if EXISTS ;
CREATE  TABLE  user (
id bigint generated BY DEFAULT  AS  IDENTITY ,
username VARCHAR (50),
password VARCHAR(50),
status varchar (50),
creationtime varchar (50)
);








